### ISSUE TITLE
game_test build fails due to TGA resource _ext.h file generation error

### ISSUE THREAD

**Issue by jpoikela** [retrodeluxe/rlengine-msx#10]
I believe the makefile causes extra characters ":=" in "game_test_tiles_ext.h" and also the generated file only contains the last created entry (the make line is not appending but overwriting)

problematic line:
https://github.com/retrodeluxe/rlengine-msx/blob/b1b619ae47fe724c5c6a588ae98948555ac57bd6/build/build_resources.mk#L132

**Comment by retrodeluxe** [comment]
thanks, is just a big typo introduced a couple of commits ago, I have just fixed it.
